"""
    Lob

    The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)?   # noqa: E501

    The version of the OpenAPI document: 1.3.0
    Contact: lob-openapi@lob.com
    Generated by: https://openapi-generator.tech
"""


import string
import unittest
from unittest_data_provider import data_provider
import warnings
import datetime as dt

import lob_python
import os
from dotenv import load_dotenv

import lob_python
from lob_python.api.bank_accounts_api import BankAccountsApi  # noqa: E501


class TestBankAccountsApi(unittest.TestCase):
    """BankAccountsApi unit test stubs"""
    

    @classmethod
    def setUpClass(self):
        load_dotenv()
        warnings.simplefilter("ignore", ResourceWarning)
        self.configuration = lob_python.Configuration(
            username = os.getenv('LOB_API_TEST_KEY')
        )
        with lob_python.ApiClient(self.configuration) as self.api_client:
            self.api = BankAccountsApi(self.api_client)  # noqa: E501

    @classmethod
    def tearDownClass(self):
        """
        Delete anything assigned as attribute to `self` in `setUpClass` here
        """
        pass

    def tearDown(self):
        pass

    def test_401(self):
        """Test case for random op with status code 401"""
        configuration = lob_python.Configuration(
            username = "Totally fake key"
        )
        with lob_python.ApiClient(configuration) as api_client:
            invalid_api = BankAccountsApi(api_client)  # noqa: E501

        with self.assertRaises(Exception) as context:
            """call random op on `invalid_api`"""
            pass
        self.assertTrue("Your API key is not valid" in context.exception.__str__())

   
    
    def test_delete_200(self):
        """Test case for delete with status code 200"""        
        
        
        
        created = self.api.create(self.editable_or_writable_name)
        deleted = self.api.delete(created.id)
        self.assertEqual(deleted.deleted, True)
        
        
        
        
        
        
        

   
    
    def test_delete_404(self):
        """Test case for delete with status code 404"""        
        
        
        
        
        
        
        
        
        
            with self.assertRaises(Exception) as context:
                self.api.delete(""""some invalid thing""")
            self.assertTrue("<SOME_ERROR_MSG>" in context.exception.__str__())

   
    
    def test_get_200(self):
        """Test case for get with status code 200"""        
        
        
        created = self.api.create(self.editable_or_writable_name)
        response = self.api.get(created.id)
        self.resource_ids.append(created.id)
        self.assertIsNotNone(response.id)
        self.assertEqual(response.id, created.id)
        
        
        
        
        
        
        
        

   
    
    def test_get_404(self):
        """Test case for get with status code 404"""        
        
        
        
        
        
        
        
        
        
            with self.assertRaises(Exception) as context:
                self.api.get(""""some invalid thing""")
            self.assertTrue("<SOME_ERROR_MSG>" in context.exception.__str__())

   
    
    def test_verify_200(self):
        """Test case for verify with status code 200"""        
        
        
        
        
        
        created = self.api.create(self.editable_or_writable_name)
        verified = self.api.verify(created.id, verification_obj)
        self.resource_ids.append(verified.id)
        self.assertIsNotNone(verified.id)
        self.assertEqual(verified.verified, True)
        
        
        
        
        

   
    
    def test_verify_404(self):
        """Test case for verify with status code 404"""        
        
        
        
        
        
        
        
        
        
            with self.assertRaises(Exception) as context:
                self.api.verify(""""some invalid thing""")
            self.assertTrue("<SOME_ERROR_MSG>" in context.exception.__str__())

   

if __name__ == '__main__':
    unittest.main()
