"""
    Lob

    The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)?   # noqa: E501

    The version of the OpenAPI document: 1.3.0
    Contact: lob-openapi@lob.com
    Generated by: https://openapi-generator.tech
"""


import string
import unittest
from unittest_data_provider import data_provider
import warnings
import datetime as dt

import lob_python
import os
from dotenv import load_dotenv

import lob_python
from lob_python.api.campaigns_api import CampaignsApi  # noqa: E501


class TestCampaignsApi(unittest.TestCase):
    """CampaignsApi unit test stubs"""
    

    @classmethod
    def setUpClass(self):
        load_dotenv()
        warnings.simplefilter("ignore", ResourceWarning)
        self.configuration = lob_python.Configuration(
            username = os.getenv('LOB_API_TEST_KEY')
        )
        with lob_python.ApiClient(self.configuration) as self.api_client:
            self.api = CampaignsApi(self.api_client)  # noqa: E501

    @classmethod
    def tearDownClass(self):
        """
        Delete anything assigned as attribute to `self` in `setUpClass` here
        """
        pass

    def tearDown(self):
        pass

    def test_401(self):
        """Test case for random op with status code 401"""
        configuration = lob_python.Configuration(
            username = "Totally fake key"
        )
        with lob_python.ApiClient(configuration) as api_client:
            invalid_api = CampaignsApi(api_client)  # noqa: E501

        with self.assertRaises(Exception) as context:
            """call random op on `invalid_api`"""
            pass
        self.assertTrue("Your API key is not valid" in context.exception.__str__())

   

if __name__ == '__main__':
    unittest.main()
