"""
    Lob

    The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)?   # noqa: E501

    The version of the OpenAPI document: 1.3.0
    Contact: lob-openapi@lob.com
    Generated by: https://openapi-generator.tech
"""


from email.headerregistry import Address
import string
import unittest
from lob_python.model.psc_use_type import PscUseType
from unittest_data_provider import data_provider
import warnings
import datetime as dt

import lob_python
import os
from dotenv import load_dotenv
from dateutil.parser import *
from lob_python.api.postcards_api import PostcardsApi  # noqa: E501
from lob_python.api.addresses_api import AddressesApi  # noqa: E501
from lob_python.model.mail_type import MailType  # noqa: E501
from lob_python.model.sort_by3 import SortBy3
from lob_python.model.merge_variables import MergeVariables  # noqa: E501
from lob_python.model.metadata_model import MetadataModel  # noqa: E501
from lob_python.model.postcard_editable import PostcardEditable  # noqa: E501
from lob_python.model.postcard_size import PostcardSize  # noqa: E501
from lob_python.model.address_editable import AddressEditable  # noqa: E501
from lob_python.model.country_extended import CountryExtended

last_month = dt.datetime.combine(
    dt.datetime.now() - dt.timedelta(weeks=4),
    dt.datetime.min.time()
)

class TestPostcardsApi(unittest.TestCase):
    """PostcardsApi unit test stubs"""
    # limit, before, after, include, date_created, metadata, size, scheduled, send_date, mail_type, sort_by
    query_params = lambda: (
        (None, None, None, ["total_count"], None, None, None, None, None, None, None),
        (None, None, None, None, {"gt": last_month}, None, None, None, None, None, None),
        (None, None, None, None, None, MetadataModel(key = "key_example"), None, None, None, None, None),
        (None, None, None, None, None, None, [PostcardSize("4x6")], None, None, None, None),
        (None, None, None, None, None, None, None, True, None, None, None),
        (None, None, None, None, None, None, None, None, {"gt": last_month.strftime("%Y-%m-%dT%H:%M:%S%z")}, None, None),
        (None, None, None, None, None, None, None, None, None, MailType("usps_first_class"), None),
        (None, None, None, None, None, None, None, None, None, None, SortBy3(date_created="asc")),
    )

    @classmethod
    def setUpClass(self):
        load_dotenv()
        now = dt.datetime.now()
        warnings.simplefilter("ignore", ResourceWarning)
        self.psc_ids = []
        self.configuration = lob_python.Configuration(
            username = os.getenv('LOB_API_TEST_KEY')
        )
        with lob_python.ApiClient(self.configuration) as self.api_client:
            self.api = PostcardsApi(self.api_client)  # noqa: E501

        self.size = PostcardSize("4x6")
        self.to_address = AddressEditable(
            name = "THING T. THING",
            address_line1 = "1313 CEMETERY LN",
            address_city = "WESTFIELD",
            address_state = "NJ",
            address_zip = "07000"
        )
        self.postcard_editable = PostcardEditable(
            to = self.to_address,
            front = "https://s3-us-west-2.amazonaws.com/public.lob.com/assets/templates/4x6_pc_template.pdf",
            back = "https://s3-us-west-2.amazonaws.com/public.lob.com/assets/templates/4x6_pc_template.pdf",
            use_type= PscUseType("marketing")
        )
        self.to2 = AddressEditable(
            name = "FESTER",
            address_line1 = "001 CEMETERY LN",
            address_line2 = "SUITE 666",
            address_city = "WESTFIELD",
            address_state = "NJ",
            address_zip = "07000"
        )
        to3 = AddressEditable(
            name = "FESTER",
            address_line1 = "666 CEMETERY LN",
            address_line2 = "SUITE 0",
            address_city = "WESTFIELD",
            address_state = "NJ",
            address_zip = "07000"
        )
        with lob_python.ApiClient(self.configuration) as api_client:
            addr_api = AddressesApi(api_client)  # noqa: E501
        deleted_addr = addr_api.create(to3)
        addr_api.delete(deleted_addr.id)
        self.deleted_addr_id = deleted_addr.id

        self.full_editable = PostcardEditable(
            to = self.to_address,
            _from = self.to2,
            size = self.size,
            description = "Dummy postcard",
            metadata=MetadataModel(
                key="key_example",
            ),
            mail_type=MailType("usps_first_class"),
            merge_variables=MergeVariables(),
            send_date=now + dt.timedelta(days=30),
            front = "https://s3-us-west-2.amazonaws.com/public.lob.com/assets/templates/4x6_pc_template.pdf",
            back = "https://s3-us-west-2.amazonaws.com/public.lob.com/assets/templates/4x6_pc_template.pdf",
            use_type= PscUseType("marketing")
        )

        self.editable_postcard2 = PostcardEditable(
            to = self.to2,
            front = "https://s3-us-west-2.amazonaws.com/public.lob.com/assets/templates/4x6_pc_template.pdf",
            back = "https://s3-us-west-2.amazonaws.com/public.lob.com/assets/templates/4x6_pc_template.pdf",
            use_type= PscUseType("marketing")
        )

        self.editable_postcard3 = PostcardEditable(
            to = to3,
            front = "https://s3-us-west-2.amazonaws.com/public.lob.com/assets/templates/4x6_pc_template.pdf",
            back = "https://s3-us-west-2.amazonaws.com/public.lob.com/assets/templates/4x6_pc_template.pdf",
            use_type= PscUseType("marketing")
        )

    @classmethod
    def tearDownClass(self):
        for i in self.psc_ids:
            self.api.cancel(i)
        del self.to_address
        del self.to2
        del self.deleted_addr_id
        del self.full_editable
        del self.postcard_editable
        del self.editable_postcard2
        del self.editable_postcard3
        del self.psc_ids
        del self.api
        del self.configuration

    def tearDown(self):
        for i in self.psc_ids:
            self.api.cancel(i)
        pass

    def test_401(self):
        """Test case for create with status code 401"""
        configuration = lob_python.Configuration(
            username = "Totally fake key"
        )
        with lob_python.ApiClient(configuration) as api_client:
            invalid_api = PostcardsApi(api_client)  # noqa: E501

        with self.assertRaises(Exception) as context:
            invalid_api.create(self.postcard_editable)
        self.assertTrue("Your API key is not valid" in context.exception.__str__())

    def test_create200(self):
        """Test case for create

        create  # noqa: E501
        """
        created_postcard = self.api.create(self.postcard_editable)
        self.psc_ids.append(created_postcard.id)
        self.assertIsNotNone(created_postcard.id)

    def test_create_full200(self):
        """Test case for create

        create  # noqa: E501
        """
        created_postcard = self.api.create(self.full_editable)
        self.psc_ids.append(created_postcard.id)
        self.assertIsNotNone(created_postcard.id)

    def test_create422_intl_from(self):
        """Test case for create

        create  # noqa: E501
        """
        intl_addr = AddressEditable(
            name = "INTL ADDRESS",
            address_line1 = "35 TOWER HILL",
            address_city = "LONDON",
            address_country = CountryExtended("GB")
        )

        invalid_postcard_editable = PostcardEditable(
            to = self.to_address,
            _from = intl_addr,
            front = "https://s3-us-west-2.amazonaws.com/public.lob.com/assets/templates/4x6_pc_template.pdf",
            back = "https://s3-us-west-2.amazonaws.com/public.lob.com/assets/templates/4x6_pc_template.pdf",
            use_type = PscUseType("marketing")
        )

        with self.assertRaises(Exception) as context:
            self.api.create(invalid_postcard_editable)
        self.assertTrue("The 'from' address must be a US address" in context.exception.__str__())

    def test_create422_deleted_address(self):
        """Test case for create

        create  # noqa: E501
        """
        invalid_postcard_editable = PostcardEditable(
            to = self.deleted_addr_id,
            front = "https://s3-us-west-2.amazonaws.com/public.lob.com/assets/templates/4x6_pc_template.pdf",
            back = "https://s3-us-west-2.amazonaws.com/public.lob.com/assets/templates/4x6_pc_template.pdf",
            use_type = PscUseType("marketing")
        )

        with self.assertRaises(Exception) as context:
            self.api.create(invalid_postcard_editable)
        self.assertTrue("deleted addresses can not be used" in context.exception.__str__())

    def test_get200(self):
        """Test case for get

        get  # noqa: E501
        """
        created_postcard = self.api.create(self.postcard_editable)
        retrieved_postcard = self.api.get(created_postcard.id)
        self.psc_ids.append(created_postcard.id)
        self.assertIsNotNone(retrieved_postcard.id)
        self.assertEqual(retrieved_postcard.id, created_postcard.id)

    def test_get404(self):
        """Test case for get

        get  # noqa: E501
        """
        with self.assertRaises(Exception) as context:
            self.api.get("psc_fake")
        self.assertTrue("postcard not found" in context.exception.__str__())

    def test_list200(self):
        """Test case for list

        list  # noqa: E501
        """
        postcard_1 = self.api.create(self.postcard_editable)
        postcard_2 = self.api.create(self.editable_postcard2)
        postcard_3 = self.api.create(self.editable_postcard3)
        self.psc_ids.append(postcard_1.id)
        self.psc_ids.append(postcard_2.id)
        self.psc_ids.append(postcard_3.id)
        listed_postcards = self.api.list(limit=2)
        self.assertLessEqual(len(listed_postcards.data), 2)
        self.assertIsNotNone(listed_postcards.data[0]['id'])
        next = listed_postcards.getNextPageToken()

        # perform test with after query param
        if next:
            listed_postcards_after = self.api.list(limit=2, after=next)
            self.assertEqual(len(listed_postcards_after.data), 2)
            self.assertIsNotNone(listed_postcards_after.data[0]['id'])
            prev = listed_postcards_after.getPreviousPageToken()
            if prev:
                listed_postcards_before = self.api.list(limit=2, before=prev)
                self.assertLessEqual(len(listed_postcards_before.data), 2)
                self.assertIsNotNone(listed_postcards_before.data[0]['id'])

    @data_provider(query_params)
    def test_list_other_query_params(self, limit, before, after, include, date_created, metadata, size, scheduled, send_date, mail_type, sort_by):
        """Test case for list with other params"""
        args = {}
        if limit:
            args["limit"] = limit

        if before:
            args["before"] = before

        if after:
            args["after"] = after

        if include:
            args["include"] = include

        if date_created:
            args["date_created"] = date_created

        if metadata:
            args["metadata"] = metadata

        if size:
            args["size"] = size

        if scheduled:
            args["scheduled"] = scheduled

        if send_date:
            args["send_date"] = send_date

        if mail_type:
            args["mail_type"] = mail_type

        if sort_by:
            args["sort_by"] = sort_by

        postcard_1 = self.api.create(self.postcard_editable)
        postcard_2 = self.api.create(self.editable_postcard2)
        postcard_3 = self.api.create(self.editable_postcard3)
        self.psc_ids.append(postcard_1.id)
        self.psc_ids.append(postcard_2.id)
        self.psc_ids.append(postcard_3.id)

        response = self.api.list(**args)

        self.assertGreaterEqual(len(response["data"]), 0)
        if include:
            self.assertIsNotNone(response["total_count"])

    def test_list422(self):
        """Test case for list

        list  # noqa: E501
        """

        postcard_1 = self.api.create(self.postcard_editable)
        postcard_2 = self.api.create(self.editable_postcard2)
        self.psc_ids.append(postcard_1.id)
        self.psc_ids.append(postcard_2.id)
        with self.assertRaises(Exception) as context:
            self.api.list(limit=101)
        self.assertTrue("Invalid value for `limit`" in context.exception.__str__())

    def test_delete200(self):
        """Test case for delete

        delete  # noqa: E501
        """
        created_postcard = self.api.create(self.postcard_editable)
        deleted_postcard = self.api.cancel(created_postcard.id)
        self.assertEqual(deleted_postcard.deleted, True)

    def test_delete404(self):
        """Test case for delete

        delete  # noqa: E501
        """
        with self.assertRaises(Exception) as context:
            self.api.cancel("psc_fake")
        self.assertTrue("postcard not found" in context.exception.__str__())


if __name__ == '__main__':
    unittest.main()
