"""
    Lob

    The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)?   # noqa: E501

    The version of the OpenAPI document: 1.3.0
    Contact: lob-openapi@lob.com
    Generated by: https://openapi-generator.tech
"""


from email.headerregistry import Address
import string
import unittest
from unittest_data_provider import data_provider
import warnings
import datetime as dt

import lob_python
import os
from dotenv import load_dotenv
from dateutil.parser import *
from lob_python.api.bank_accounts_api import BankAccountsApi  # noqa: E501
from lob_python.model.bank_account_writable import BankAccountWritable  # noqa: E501
from lob_python.model.bank_account_verify import BankAccountVerify  # noqa: E501
from lob_python.model.bank_type_enum import BankTypeEnum  # noqa: E501
from lob_python.model.metadata_model import MetadataModel


class TestBankAccountsApi(unittest.TestCase):
    """BankAccountsApi unit test stubs"""
    # limit, before, after, include, date_created, metadata
    query_params = lambda: (
        (None, None, None, ["total_count"], None, None),
        (None, None, None, None, {"gt": dt.datetime.combine(
            dt.datetime.now() - dt.timedelta(weeks=4),
            dt.datetime.min.time()
        )}, None),
        (None, None, None, None, None, MetadataModel(key = "key_example"))
    )

    @classmethod
    def setUpClass(self):
        load_dotenv()
        warnings.simplefilter("ignore", ResourceWarning)
        self.bank_ids = []
        self.configuration = lob_python.Configuration(
            username = os.getenv('LOB_API_TEST_KEY')
        )
        with lob_python.ApiClient(self.configuration) as self.api_client:
            self.api = BankAccountsApi(self.api_client)  # noqa: E501

        self.bank_writable  = BankAccountWritable(
            routing_number = "322271627",
            account_number = "123456789",
            signatory = "Sigourney Lobster",
            account_type = BankTypeEnum("individual")
        )

        self.bank_writable2 = BankAccountWritable(
            routing_number = "322271627",
            account_number = "123456789",
            signatory = "Sinead Connor",
            account_type = BankTypeEnum("individual")
        )

    @classmethod
    def tearDownClass(self):
        for i in self.bank_ids:
            self.api.delete(i)
        del self.bank_writable
        del self.bank_writable2
        del self.api
        del self.configuration
        del self.bank_ids

    def tearDown(self):
        for i in self.bank_ids:
            self.api.delete(i)
        pass

    def test_401(self):
        """Test case for create with status code 401"""
        configuration = lob_python.Configuration(
            username = "Totally fake key"
        )
        with lob_python.ApiClient(configuration) as api_client:
            invalid_api = BankAccountsApi(api_client)  # noqa: E501
        with self.assertRaises(Exception) as context:
            invalid_api.create(self.bank_writable)
        self.assertTrue("Your API key is not valid" in context.exception.__str__())

    def test_create200(self):
        """Test case for create

        create  # noqa: E501
        """
        created_bank = self.api.create(self.bank_writable)
        self.bank_ids.append(created_bank.id)
        self.assertIsNotNone(created_bank.id)

    def test_create422_invalid_routing_number(self):
        """Test case for create

        create  # noqa: E501
        """
        with self.assertRaises(Exception) as context:
            self.api.create(BankAccountWritable(
                routing_number = "1234567890",
                account_number = "123456789",
                signatory = "Sinead Connor",
                account_type = BankTypeEnum("individual")
            ))
        self.assertTrue("Invalid value for `routing_number`" in context.exception.__str__())

    def test_verify200(self):
        """Test case for get

        get  # noqa: E501
        """
        bank_verify = BankAccountVerify(
            amounts = [11, 35]
        )
        created_bank = self.api.create(self.bank_writable)
        verified_bank_acc = self.api.verify(created_bank.id, bank_verify)
        self.bank_ids.append(verified_bank_acc.id)
        self.assertIsNotNone(verified_bank_acc.id)
        self.assertEqual(verified_bank_acc.verified, True)

    def test_verify404(self):
        """Test case for get

        get  # noqa: E501
        """
        bank_verify = BankAccountVerify(
            amounts = [11, 35]
        )
        with self.assertRaises(Exception) as context:
            self.api.verify("bank_fakeId", bank_verify)
        self.assertTrue("bank account not found" in context.exception.__str__())

    def test_get200(self):
        """Test case for get

        get  # noqa: E501
        """
        created_bank = self.api.create(self.bank_writable)
        retrieved_bank_account = self.api.get(created_bank.id)
        self.bank_ids.append(created_bank.id)
        self.assertIsNotNone(retrieved_bank_account.id)
        self.assertEqual(retrieved_bank_account.id, created_bank.id)

    def test_get404(self):
        """Test case for get

        get  # noqa: E501
        """
        with self.assertRaises(Exception) as context:
            self.api.get("bank_fake")
        self.assertTrue("bank account not found" in context.exception.__str__())

    def test_list200(self):
        """Test case for list

        list  # noqa: E501
        """

        bank_writable3 = BankAccountWritable(
            routing_number = "322271627",
            account_number = "123456789",
            signatory = "Mr Potato",
            account_type = BankTypeEnum("individual")
        )

        bank_1 = self.api.create(self.bank_writable)
        bank_2 = self.api.create(self.bank_writable2)
        bank_3 = self.api.create(bank_writable3)
        self.bank_ids.append(bank_1.id)
        self.bank_ids.append(bank_2.id)
        self.bank_ids.append(bank_3.id)
        listed_banks = self.api.list(limit=2)
        self.assertLessEqual(len(listed_banks.data), 2)
        self.assertIsNotNone(listed_banks.data[0]['id'])
        next = listed_banks.getNextPageToken()

        # perform test with after query param
        if next:
            listed_banks_after = self.api.list(limit=2, after=next)
            self.assertEqual(len(listed_banks_after.data), 2)
            self.assertIsNotNone(listed_banks_after.data[0]['id'])
            prev = listed_banks_after.getPreviousPageToken()
            if prev:
                listed_banks_before = self.api.list(limit=2, before=prev)
                self.assertLessEqual(len(listed_banks_before.data), 2)
                self.assertIsNotNone(listed_banks_before.data[0]['id'])

    @data_provider(query_params)
    def test_list_other_query_params(self, limit, before, after, include, date_created, metadata):
        """Test case for list with other params"""

        bank_writable3 = BankAccountWritable(
            routing_number = "322271627",
            account_number = "123456789",
            signatory = "Mr Potato",
            account_type = BankTypeEnum("individual"),
            metadata = MetadataModel(key = "key_example")
        )

        bank_1 = self.api.create(self.bank_writable)
        bank_2 = self.api.create(self.bank_writable2)
        bank_3 = self.api.create(bank_writable3)
        self.bank_ids.append(bank_1.id)
        self.bank_ids.append(bank_2.id)
        self.bank_ids.append(bank_3.id)

        args = {}
        if limit:
            args["limit"] = limit

        if before:
            args["before"] = before

        if after:
            args["after"] = after

        if include:
            args["include"] = include

        if date_created:
            args["date_created"] = date_created

        if metadata:
            args["metadata"] = metadata
        response = self.api.list(**args)

        self.assertGreater(len(response["data"]), 0)
        if include:
            self.assertIsNotNone(response["total_count"])

        self.assertIsNotNone(response.data[0]['id'])

    def test_list422(self):
        """Test case for list

        list  # noqa: E501
        """

        bank_1 = self.api.create(self.bank_writable)
        bank_2 = self.api.create(self.bank_writable2)
        self.bank_ids.append(bank_1.id)
        self.bank_ids.append(bank_2.id)
        with self.assertRaises(Exception) as context:
            self.api.list(limit=101)
        self.assertTrue("Invalid value for `limit`" in context.exception.__str__())

    def test_delete200(self):
        """Test case for delete

        delete  # noqa: E501
        """
        created_bank = self.api.create(self.bank_writable)
        deleted_bank = self.api.delete(created_bank.id)
        self.assertEqual(deleted_bank.deleted, True)

    def test_delete404(self):
        """Test case for delete

        delete  # noqa: E501
        """
        with self.assertRaises(Exception) as context:
            self.api.delete("bank_fake")
        self.assertTrue("bank account not found" in context.exception.__str__())


if __name__ == '__main__':
    unittest.main()
